### PR TITLE
Fixed broken links.

### PR DESCRIPTION
**Pull request by senmm**
Fix links.

### CODE REVIEW

**Comment by 8398a7** [comment]
Thanks for the PR.
It seems to be working correctly in my environment, how does it work in yours?

**Comment by senmm** [comment]
It's fine in my environment.👍

**Comment by 8398a7** [comment]
Sorry, I misled you.
I can confirm that it is working fine before the modification, how is it in your environment?

**Comment by senmm** [comment]
Sorry for my misunderstanding.
My browser show me 404 page, it is Google Chrome v100.0.4896.127.

**Comment by 8398a7** [comment]
My version of chrome is also 100.0.4896.127.
And there was no occurrence of a 404.

I have tried it in the incognito browser and it works fine.

Is it possible that some chrome extension is affecting it?
Could you check it with the incognito browser as well?

**Comment by senmm** [comment]
My chrome extension is only Innovative Exams Screensharing. This extension is a video sharing function for CKA/CKAD.
I tried to check it with secret window and turn off extension and I can see 404 page.

**Comment by 8398a7** [comment]
Are you by any chance browsing from the following page?
https://github.com/8398a7/action-slack/blob/master/docs/content/index.md

This markdown is intended to be viewed from a website.
https://action-slack.netlify.app/

**Comment by senmm** [comment]
I'm so sorry that I have browsed following page.
https://github.com/8398a7/action-slack/blob/master/docs/content/index.md.

**Comment by 8398a7** [comment]
Ok, thank you.

**Pull request closed without merging**
