### PR TITLE
Improve workflowRun Slack notification title for clarity

### PR DESCRIPTION
**Pull request by ham0215**
Currently, the Slack notification title for workflowRuns is the same as the workflow title. This makes it difficult to quickly understand the purpose of the notification from the Slack message.

This pull request proposes to change the workflowRun notification title to be more informative and distinct from the workflow title. This will improve the clarity of Slack notifications and make it easier to identify the specific action that triggered the notification.

### CODE REVIEW

**Comment by ham0215** [comment]
@8398a7 
Could you please confirm this?

**Comment by ham0215** [comment]
Sorry, I'm not sure why, but Codecov seems to be throwing an error and causing CI to fail.

https://github.com/8398a7/action-slack/actions/runs/11235648383/job/31234107129?pr=255
```
==> Uploading reports
/home/runner/work/action-slack/action-slack/node_modules/codecov/lib/codecov.js:212
      } else if (result.split('\n').length !== 2) {
                        ^

TypeError: result.split is not a function
    at /home/runner/work/action-slack/action-slack/node_modules/codecov/lib/codecov.js:212:25
    at /home/runner/work/action-slack/action-slack/node_modules/teeny-request/build/src/index.js:217:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by 8398a7** [comment]
Here(https://github.com/8398a7/action-slack/pull/256) is the corrected version, so please merge the changes from master.

**Comment by ham0215** [comment]
Thanks for the fix! I've merged the changes from the master branch.

**Pull request merged**
